name: Basic workflow
on:
  push:                     # Triggered on Push events
jobs:
  build:
    runs-on: ubuntu-latest  # Will run on a Ubuntu VM
    steps:
    - name: Welcome
      run: echo "Sample workflow"   
