name:  Workflow-5-matrix
on:
  workflow_dispatch
jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12]
        os: [ubuntu-22.04, ubuntu-20.04, windows-latest]
        include:
          - os: ubuntu-22.04
            version: 14
          - os: ubuntu-latest
            version: 16
        exclude:
          - os: ubuntu-20.04
            version: 12
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "OS_${{ matrix.os }} version_${{ matrix.version }}"
#      - uses: actions/setup-node@v4
#        with:
#          node-version: ${{ matrix.version }}
